### ISSUE TITLE
EntityPlayerSP error when running on server

### ISSUE THREAD

**Issue by ZeekDaGeek** [thedarkcolour/Future-MC#119]
I'm not too sure why but whenever I attempt to run Future MC on a 1.12.2 server I get the following error, it seems that the client / common proxies aren't working?

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLModule (mdxlib-3.0.0.11.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  Techguns Core (Techguns-Mod-1.12.2.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.65-core.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/17/20 4:22 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at mod.mcreator.mcreator_bell.<clinit>(mcreator_bell.java:33)
	at mod.mcreator.futureminecraft.<clinit>(futureminecraft.java:224)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 35 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@30cecdca from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 37 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-1062.18.1.el7.x86_64
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 76731344 bytes (73 MB) / 1093664768 bytes (1043 MB) up to 7456948224 bytes (7111 MB)
	JVM Flags: 2 total; -Xmx8000M -Xms128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                            | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2            | minecraft.jar                                     | None                                     |
	| LC    | mcp                               | 9.42              | minecraft.jar                                     | None                                     |
	| LC    | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LC    | forge                             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LC    | obfuscate                         | 0.2.6             | minecraft.jar                                     | None                                     |
	| LC    | tnt_utilities_core                | 1.2.3             | minecraft.jar                                     | None                                     |
	| LC    | techguns_core                     | 1.12.2-1.0        | minecraft.jar                                     | None                                     |
	| LC    | securitycraft                     | v1.8.10           | [1.12.2]+SecurityCraft+v1.8.10.jar                | None                                     |
	| LC    | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | baubles                           | 1.5.2             | Baubles-Mod-1.12.2.jar                            | None                                     |
	| LC    | betterslabsmod                    | 0.0.7             | Better-Slabs-Mod-1.12.2.jar                       | None                                     |
	| LC    | patchouli                         | 1.0-6             | Patchouli-Mod-1.12.2.jar                          | None                                     |
	| LC    | llibrary                          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | bewitchment                       | @VERSION@         | Bewitchment-Mod-1.12.2.jar                        | None                                     |
	| LC    | bibliocraft                       | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LC    | biomesoplenty                     | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
	| LC    | blockcraftery                     | 1.12.2-1.1.0      | Blockcraftery-Mod-1.12.2.jar                      | None                                     |
	| LC    | bookshelf                         | 2.3.577           | Bookshelf-1.12.2-2.3.577.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | zawa                              | 1.12.2-1.6.0      | zawa+-+1.6.0+(1.12.2).jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LC    | bookworm                          | 1.12.2-2.2.0      | bookworm+-+2.2.0+(1.12.2).jar                     | None                                     |
	| LC    | carryon                           | 1.12.1            | CarryOn+MC1.12.2+v1.12.1.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LC    | chisel                            | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LC    | chromaticfoliage                  | 1.1.0             | Chromatic-Foliage-Mod-1.12.2.jar                  | None                                     |
	| LC    | craftstudioapi                    | 1.0.0             | CraftStudio-API-1.12.1.jar                        | None                                     |
	| LC    | customnpcs                        | 1.12              | CustomNPCs-1.12.jar                               | None                                     |
	| LC    | props                             | 2.6.2             | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.65     | EnderCore-1.12.2-0.5.65.jar                       | None                                     |
	| LC    | enderio                           | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderiointegrationtic             | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderiobase                       | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderioconduits                   | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderiointegrationforestry        | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderiointegrationticlate         | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderiomachines                   | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | enderiopowertools                 | 5.0.50            | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	| LC    | immersiveengineering              | 0.12-88           | ImmersiveEngineering-0.12-88.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | engineersdoors                    | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar                  | None                                     |
	| LC    | golems                            | 7.1.4             | ExtraGolems-1.12-7.1.4.jar                        | None                                     |
	| LC    | cfm                               | 6.2.0             | furniture-6.2.0-1.12.2.jar                        | None                                     |
	| L     | futureminecraft                   | 1.1.3             | Future-Versions-Mod-1.12.2.jar                    | None                                     |
	| L     | ichunutil                         | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                        | None                                     |
	| L     | lightingwand                      | 1.0.4             | LightingWand-1.0.4.jar                            | None                                     |
	| L     | locks                             | 2.2.1             | Locks-2.2.1.jar                                   | None                                     |
	| L     | lootoverhaul                      | 1.2               | LootOverhaul-1.2.jar                              | None                                     |
	| L     | malisiscore                       | 1.12.2-6.4.0      | MalisisCore-1.12.2.jar                            | None                                     |
	| L     | malisisadvert                     | 1.12.2-6.1.0      | MalisisAdvert-Mod-1.12.2.jar                      | None                                     |
	| L     | malisisdoors                      | 1.12.2-7.3.0      | MalisisDoors-Mod-1.12.2.jar                       | None                                     |
	| L     | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                           | None                                     |
	| L     | mdxlib                            | 3.0.0.11          | mdxlib-3.0.0.11.jar                               | None                                     |
	| L     | minetraps                         | 1.0.0             | MineTraps-1.12.2-(v.1.0.0).jar                    | None                                     |
	| L     | mob_grinding_utils                | 0.3.12            | Mob-Grinding-Utils-Mod-1.12.2.jar                 | None                                     |
	| L     | moreexplosives                    | 1.0.2             | More+Explosives+V1.0.2.jar                        | None                                     |
	| L     | multimob                          | 1.0.5             | multimob-1.0.5.jar                                | None                                     |
	| L     | pinkmod                           | 2019.3-1.3.2      | pinkmod-0.0.5.jar                                 | None                                     |
	| L     | potioncore                        | 1.8_for_1.12.2    | PotionCore-1.8_for_1.12.2.jar                     | None                                     |
	| L     | secretroomsmod                    | 5.3.2             | Secret-Rooms-Mod-1.12.2.jar                       | None                                     |
	| L     | simpledimensions                  | 1.3.1             | SimpleDimensions-MC1.12-1.3.1.jar                 | None                                     |
	| L     | simplemagnet                      | 1.12.2-1.3.12     | simplemagnet-1.12.2-1.3.12.jar                    | None                                     |
	| L     | soccer                            | 1.0               | Soccer-Mod-1.12.2.jar                             | None                                     |
	| L     | techguns                          | 2.0.1.2           | Techguns-Mod-1.12.2.jar                           | None                                     |
	| L     | thutcore                          | 5.21.0            | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| L     | thutcore_compat                   | 1.0               | thutcore-1.12.2-5.21.0.jar                        | None                                     |
	| L     | thuttech                          | 6.1.6             | thuttech-1.12.2-6.1.6.jar                         | None                                     |
	| L     | tnt_utilities                     | 1.2.3             | tnt_utilities-mc1.12-1.2.3.jar                    | None                                     |
	| L     | trackapi                          | 1.1               | TrackAPI-1.1_1.12.jar                             | None                                     |
	| L     | trainsmod                         | 0.1.6             | trainsmod-0.1.6.jar                               | None                                     |
	| L     | ultimate_unicorn_mod              | 1.5.16            | ultimate_unicorn_mod-1.12.2-1.5.16.jar            | None                                     |
	| L     | vehicle                           | 0.36.0            | vehicle-mod-0.36.0-1.12.2.jar                     | None                                     |
	| L     | worldedit                         | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| L     | zeiyocraft                        | 0.8.4             | ZeiyoCraft-Mod-1.12.2.jar                         | None                                     |
	| L     | candymod                          | 1.1.5             | candyworld-1.1.5.jar                              | None                                     |
	| L     | shetiphiancore                    | 3.5.9             | shetiphiancore-1.12.0-3.5.9.jar                   | None                                     |
	| L     | additions                         | 0.4.7             | Additions-0.4.7.jar                               | None                                     |
	| L     | mysticallib                       | 1.12.2-1.3.2      | mysticallib-1.12.2-1.3.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
FMLModule (mdxlib-3.0.0.11.jar)
  com.asx.mdx.AccessTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Techguns Core (Techguns-Mod-1.12.2.jar)
  techguns.core.TechgunsASMTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.65-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by ZeekDaGeek** [comment]
Similar name, wrong mod. Sorry <3
