### ISSUE TITLE
Ticking Entity Crash on Bee

### ISSUE THREAD

**Issue by TheTennessee** [thedarkcolour/Future-MC#139]
I had my game crash suddenly just now as I was running around for the first time with the new patch. I have a bunch of bees from the previous version around my base, and they often fly over my crops (the setup is to have them pollinate like in 1.15). Anyhow, here's the crash report:

[01:14:39] [Client thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\TheTennessee\AppData\Roaming\.technic\modpacks\the-1122-pack\crash-reports\crash-2020-05-16_01.14.02-server.txt
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2020-05-16 01:14:39 EDT
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=minecraft:beetroots, properties=[age]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at thedarkcolour.futuremc.api.BeePollinationHandler$Companion$$special$$inlined$create$2.pollinateCrop(BeePollinationHandler.kt:121)
    at thedarkcolour.futuremc.entity.bee.EntityBee$AIGrowCrops.updateTask(EntityBee.java:594)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at thedarkcolour.futuremc.entity.bee.EntityBee.onLivingUpdate(EntityBee.java:296)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at thedarkcolour.futuremc.entity.bee.EntityBee.onUpdate(EntityBee.java:183)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbo000(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: futuremc:bee (thedarkcolour.futuremc.entity.bee.EntityBee)
  Entity ID: 662
  Entity Name: Bee
  Entity's Exact location: -207.70, 35.30, 395.83
  Entity's Block location: World: (-208,35,395), Chunk: (at 0,2,11 in -13,24; contains blocks -208,0,384 to -193,255,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: 0.01, 0.00, 0.06
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {NoGravity:1b,HurtByTimestamp:101,ForgeData:{thebetweenlands.has_no_equipment:1b},FlowerPos:{X:-210,Y:34,Z:396},HasStung:0b,RelativeAABB:[-0.3499999940395355d,0.0d,-0.3499999940395355d,0.3499999940395355d,0.699999988079071d,0.3499999940395355d],Attributes:[{Base:-2.0d,Name:"tc.mobmod"},{Base:0.0d,Name:"tc.mobmodtaint"},{Base:0.0d,Name:"generic.scales"},{Base:1.0d,Name:"generic.physicalDamageRate"},{Base:1.0d,Name:"generic.fireDamageRate"},{Base:0.0d,Name:"generic.fireAspect"},{Base:1.0d,Name:"generic.barehandedPower"},{Base:0.0d,Name:"generic.witchburn"},{Base:0.0d,Name:"generic.attraction"},{Base:0.0d,Name:"generic.attraction_generation"},{Base:10.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.30000001192092896d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Modifiers:[{UUIDMost:3127311971608248702L,UUIDLeast:-8637076718742248328L,Amount:0.038944835788379546d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:0.6000000238418579d,Name:"generic.flyingSpeed"},{Base:2.0d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,LoveCauseLeast:-6314010343147901984L,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,InLove:0,DeathTime:0s,ForgeCaps:{"thebetweenlands:entity_gems":{gems:[]},"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:1},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice and Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0,DreadPortalZ:0,DreadPortalY:0,DreadPortalX:0},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"thebetweenlands:puppet":{ticks:0,guard:0b,recruitmentCost:0,stay:0b},"twilightforest:cap_shield":{permshields:0,tempshields:0},"thebetweenlands:equipment":{amuletSlots:1},"thaumicaugmentation:portal_state":{inPortal:0b},"cavern:portal_cache":{LastPos:[],LastDim:[]},"pneumaticcraft:hacking":{}},HandDropChances:[0.085f,0.085f],CannotEnterHiveTicks:0,PersistenceRequired:0b,Age:0,TicksSincePollination:1803901,Anger:0,Motion:[0.013981842712963582d,0.0d,0.06056556823271941d],Leashed:0b,UUIDLeast:-5965778735842038315L,Health:10.0f,HurtBy:"1b0dae6e-45d1-45f1-a860-210bc486ebe0",HasNectar:1b,LeftHanded:0b,Air:300s,OnGround:0b,Dimension:0,LoveCauseMost:1949406002362271217L,Rotation:[56.38159f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:301896473228365283L,Pos:[-207.69519370220743d,35.30000001192093d,395.82825493299976d],Fire:-1s,ArmorItems:[{},{},{},{}],CropsGrownSincePollination:0,CanPickUpLoot:0b,HurtTime:0s,HivePos:{X:-202,Y:35,Z:398}}

**Comment by TheTennessee** [comment]
P.S. It seems to only be the beetroot that does it. I took out the beetroots and the rest of my crops are not crashing. So for now I am just not farming them to prevent a crash.

**Comment by thedarkcolour** [comment]
Whoops.

**Comment by thedarkcolour** [comment]
I was sloppy copy + pasting my code for crop pollination.

**Comment by thedarkcolour** [comment]
I have a bunch of homework so I'll fix it tomorrow. It's an easy fix, don't worry about the update being super delayed.

**Comment by TheTennessee** [comment]
No worries. It hasn't prevented me from getting into my world, and I temporarily solved it for now. So all is good. The bright side, I had a TON of crops out there, wheat, potatos, carrots, and tons of mod crops as well like from pam's harvestcraft and growthcraft. It was really only beets that threw a fit.

**Comment by thedarkcolour** [comment]
Growthcraft and harvestcraft will have to add their own compatibility, since crop pollination is done through code.

**Comment by thedarkcolour** [comment]
Now that I'm reading my code it seems the crash could also occur with pumkin stems and melon stems.

**Comment by thedarkcolour** [comment]
Fixed in 0.2.2

**Comment by TheTennessee** [comment]
Awesome. Thanks a ton.
