### ISSUE TITLE
Upgrading versions causes an issue on server

### ISSUE THREAD

**Issue by AechtRob** [thedarkcolour/Future-MC#147]
Hi - We have a 1.12.2 server world with an older futuremc version installed: future-mc-0.1.13.jar

When I swap out the mod for the latest one (Future MC 1.12.2 0.2.2 ) and add in Forgelin I get the errors below on the server, after it remaps various things, and flags futuremc ones as missing. Can you suggest what I can do please? We are using many blocks from the old mod version in the world and so can't lose them or we'll break the world.

`[10:33:47] [Server thread/DEBUG] [FML]: There are 139 mappings missing - attempting a mod remap
[10:33:47] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$MissingMappings@5d164f3f:
java.lang.NullPointerException: Remap target can not be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.remap(RegistryEvent.java:210) ~[RegistryEvent$MissingMappings$Mapping.class:?]
	at thedarkcolour.futuremc.world.OldWorldHandler.remap(OldWorldHandler.kt:134) ~[OldWorldHandler.class:?]
	at thedarkcolour.futuremc.world.OldWorldHandler.onOldEntityLoad(OldWorldHandler.kt:114) ~[OldWorldHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_292_OldWorldHandler_onOldEntityLoad_MissingMappings.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$20(GameData.java:684) ~[GameData.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:1.8.0_251]
	at java.util.Iterator.forEachRemaining(Unknown Source) [?:1.8.0_251]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) [?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) [?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) [?:1.8.0_251]
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:679) [GameData.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:172) [FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:423) [FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bfc.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bfb.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:228) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[10:33:47] [Server thread/ERROR] [FML]: Index: 8 Listeners:
[10:33:47] [Server thread/ERROR] [FML]: 0: NORMAL
[10:33:47] [Server thread/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@51ddf407
[10:33:47] [Server thread/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@25fae98f
[10:33:47] [Server thread/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@43005024
[10:33:47] [Server thread/ERROR] [FML]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@2c8080cc
[10:33:47] [Server thread/ERROR] [FML]: 5: net.minecraftforge.fml.common.eventhandler.EventBus$1@12c32497
[10:33:47] [Server thread/ERROR] [FML]: 6: net.minecraftforge.fml.common.eventhandler.EventBus$1@600711d1
[10:33:47] [Server thread/ERROR] [FML]: 7: net.minecraftforge.fml.common.eventhandler.EventBus$1@21c7fc85
[10:33:47] [Server thread/ERROR] [FML]: 8: net.minecraftforge.fml.common.eventhandler.EventBus$1@9e98e91
[10:33:47] [Server thread/ERROR] [FML]: 9: net.minecraftforge.fml.common.eventhandler.EventBus$1@285f4a7
[10:33:47] [Server thread/ERROR] [FML]: 10: net.minecraftforge.fml.common.eventhandler.EventBus$1@5ad4f4bf
[10:33:47] [Server thread/ERROR] [FML]: 11: net.minecraftforge.fml.common.eventhandler.EventBus$1@446908b4
[10:33:47] [Server thread/ERROR] [FML]: 12: net.minecraftforge.fml.common.eventhandler.EventBus$1@1b18bae
[10:33:47] [Server thread/ERROR] [FML]: 13: net.minecraftforge.fml.common.eventhandler.EventBus$1@2c3c77f3
[10:33:47] [Server thread/ERROR] [FML]: 14: net.minecraftforge.fml.common.eventhandler.EventBus$1@51b00fc7
[10:33:47] [Server thread/ERROR] [FML]: 15: net.minecraftforge.fml.common.eventhandler.EventBus$1@5d1091ed
[10:33:47] [Server thread/ERROR] [FML]: 16: net.minecraftforge.fml.common.eventhandler.EventBus$1@50f18d1a
[10:33:47] [Server thread/ERROR] [FML]: 17: net.minecraftforge.fml.common.eventhandler.EventBus$1@1fbdeb18
[10:33:47] [Server thread/ERROR] [FML]: 18: net.minecraftforge.fml.common.eventhandler.EventBus$1@4e22011f
[10:33:47] [Server thread/ERROR] [FML]: 19: net.minecraftforge.fml.common.eventhandler.EventBus$1@17647ecf
[10:33:47] [Server thread/ERROR] [net.minecraft.world.storage.SaveFormatOld]: Exception reading .\world\level.dat
java.lang.NullPointerException: Remap target can not be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.remap(RegistryEvent.java:210) ~[RegistryEvent$MissingMappings$Mapping.class:?]
	at thedarkcolour.futuremc.world.OldWorldHandler.remap(OldWorldHandler.kt:134) ~[OldWorldHandler.class:?]
	at thedarkcolour.futuremc.world.OldWorldHandler.onOldEntityLoad(OldWorldHandler.kt:114) ~[OldWorldHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_292_OldWorldHandler_onOldEntityLoad_MissingMappings.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$20(GameData.java:684) ~[GameData.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:679) ~[GameData.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:172) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:423) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bfc.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bfb.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:228) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[10:33:47] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.`

**Comment by AechtRob** [comment]
Just to add to this... if I take a copy of the server and world and everything and then try allowing this to run with /fml confirm the world does indeed get corrupted, with random blocks from random mods replacing other ones. I think there is mapping missing from the mod to allow updates to it :/

**Comment by thedarkcolour** [comment]
I'll do some more testing, I'm really sorry about world corruption

**Comment by thedarkcolour** [comment]
A workaround is to first use 0.2.1 then update to 0.2.2

**Comment by AechtRob** [comment]
Lucky for me I ran a thorough test in a copy server before I tried it on our actual world :P

I'll see what going via the intermediate version does and let you know.

**Comment by SanjivanM** [comment]
Yeah, same here, also came to report this.  FML throws a "reading backup level.dat" error as well (actual level.dat was also present)  This seems like the new FutureMC version messes with Block ID's (and possibly entity ID's)...
