### ISSUE TITLE
[1.12.2] Pufferfish crash

### ISSUE THREAD

**Issue by BastiPro10** [thedarkcolour/Future-MC#182]
I have a server where the ancient debris worked correctly, but from one day to the next it disappeared from the creative menu and all the generated ores of this mineral disappeared from the world. As much as I searched there was not a single ore of ancient debris. In addition there is a bug that disconnects players from the server when interacting with puffer fish.

I hope they can fix it as soon as possible.
Regards.

This is what I get on the console when a player is disconnected by the puffefish. The bug occurs when the puffer fish inflates to attack the player.

[16:11:08] [Netty Epoll Server IO #1/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: ConnectionProtocol unknown: thedarkcolour.futuremc.entity.fish.pufferfish.EntityPufferfish$SPacketSting@554ee7df
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[MessageToByteEncoder.class:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[ChannelDuplexHandler.class:?]
at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:548) ~[NetworkDispatcher.class:4695040]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[ChannelDuplexHandler.class:?]
at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[ChannelDuplexHandler.class:?]
at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:256) ~[gw$4.class:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321) ~[?:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [EpollEventLoop.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.RuntimeException: ConnectionProtocol unknown: thedarkcolour.futuremc.entity.fish.pufferfish.EntityPufferfish$SPacketSting@554ee7df
at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:31) ~[ha.class:?]
at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:14) ~[ha.class:?]
at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243) ~[?:?]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[MessageToByteEncoder.class:?]
... 39 more
[16:11:08] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: BastiPro10 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: ConnectionProtocol unknown: thedarkcolour.futuremc.entity.fish.pufferfish.EntityPufferfish$SPacketSting@554ee7df
[16:11:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: BastiPro10 left the game

**Comment by thedarkcolour** [comment]
Can you post a crash log of the pufferfish crash?
