### ISSUE TITLE
[1.12.2] Crash with Grindstone

### ISSUE THREAD

**Issue by TheDentt** [thedarkcolour/Future-MC#229]
-- Head --
Thread: Client thread
Stacktrace:
	at thedarkcolour.futuremc.container.ContainerGrindstone.handleCrafting(ContainerGrindstone.java:173)
	at thedarkcolour.futuremc.container.ContainerGrindstone$1.onContentsChanged(ContainerGrindstone.java:39)
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:60)
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

was trying to disenchant a sword, as soon as I put it in the grindstone interface, game crashes, happens on my server to my friends as well

**Comment by thedarkcolour** [comment]
What version of the mod are you using

**Comment by thedarkcolour** [comment]
Can you provide a log?

**Comment by democat3457** [comment]
also thats not the full crash report
