### ISSUE TITLE
[1.12.2] Breaking Berry bush Crashes Server

### ISSUE THREAD

**Issue by Lerronin** [thedarkcolour/Future-MC#239]
Having an eternal server crash catastrophically everytime a berry bush gets broken somewhere in the world.

```
Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@6ea6ece0:

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method thedarkcolour.futuremc.block.villagepillage.SweetBerryBushBlock.getPickBlock, parameter target
```
[crash-2021-05-26_01.23.44-server.txt](https://github.com/thedarkcolour/Future-MC/files/6543273/crash-2021-05-26_01.23.44-server.txt)

**Comment by thedarkcolour** [comment]
Oops.

**Comment by thedarkcolour** [comment]
Do you have a full stacktrace? Seems like a mod isn't doing something right on their end either

**Comment by Handeril** [comment]
I checked out the file, the full error is the following:

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method thedarkcolour.futuremc.block.villagepillage.SweetBerryBushBlock.getPickBlock, parameter target
    at thedarkcolour.futuremc.block.villagepillage.SweetBerryBushBlock.getPickBlock(SweetBerryBushBlock.kt)
    at ht.treechop.common.util.ChopUtil.isBlockLeaves(ChopUtil.java:80)
    at ht.treechop.common.util.ChopUtil.isBlockLeaves(ChopUtil.java:74)
    at ht.treechop.common.util.ChopUtil.lambda$null$5(ChopUtil.java:201)
    at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
    at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1249)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at ht.treechop.common.util.ChopUtil.getConnectedBlocks(ChopUtil.java:116)
    at ht.treechop.common.util.ChopUtil.getConnectedBlocks(ChopUtil.java:125)
    at ht.treechop.common.util.ChopUtil.getChopResult(ChopUtil.java:198)
    at ht.treechop.common.util.ChopUtil.getChopResult(ChopUtil.java:186)
    at ht.treechop.common.Common.onBreakEvent(Common.java:58)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3283_Common_onBreakEvent_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:851)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:283)
    at net.minecraft.server.management.PlayerInteractionManager.updateBlockRemoving(PlayerInteractionManager.java:109)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:316)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642)
    at net.minecraft.world.World.updateEntities(World.java:1737)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by democat3457** [comment]
@Lerronin have you tried updating treechop to https://www.curseforge.com/minecraft/mc-mods/treechop/files/3323959
