### ISSUE TITLE
[1.12.2] Cannot Trade with Entities

### ISSUE THREAD

**Issue by jniraethd** [thedarkcolour/Future-MC#265]
Minecraft Version 1.12.2
Mod version 0.2.7.3

Server console gives Exception Error when trying to trade with entities (vanilla and modded) and will not open the trading menu

`[17:09:42] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerContainerEvent$Open@1badefd9:
java.lang.NoSuchMethodError: net.minecraft.inventory.Container.func_82847_b(Lnet/minecraft/inventory/IContainerListener;)V
        at thedarkcolour.futuremc.event.Events.onContainerOpen(Events.kt:352) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events.access$onContainerOpen(Events.kt:91) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events$registerEvents$$inlined$addListener$7.invoke(Util.kt:243) ~[Events$registerEvents$$inlined$addListener$7.class:0.2.7.3]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:919) [oq.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:273) [ady.class:?]
        at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) [vq.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) [aed.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1075) [pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:09:42] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[17:09:42] [Server thread/ERROR] [FML]: 0: NORMAL
[17:09:42] [Server thread/ERROR] [FML]: 1: ASM: class slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation onCraftingStationGuiOpened(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[17:09:42] [Server thread/ERROR] [FML]: 2: thedarkcolour.futuremc.event.Events$registerEvents$$inlined$addListener$7@5b91fc60
[17:09:42] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.inventory.Container.func_82847_b(Lnet/minecraft/inventory/IContainerListener;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NoSuchMethodError: net.minecraft.inventory.Container.func_82847_b(Lnet/minecraft/inventory/IContainerListener;)V
        at thedarkcolour.futuremc.event.Events.onContainerOpen(Events.kt:352) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events.access$onContainerOpen(Events.kt:91) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events$registerEvents$$inlined$addListener$7.invoke(Util.kt:243) ~[Events$registerEvents$$inlined$addListener$7.class:0.2.7.3]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:919) ~[oq.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:273) ~[ady.class:?]
        at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1075) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more`

**Comment by Papito541** [comment]
The same thing happens on my server, but I have the come live mod, I don't know if it's incompatibility or mod error

**Comment by thedarkcolour** [comment]
For now, disable the config option for new villager trading screen until I put out another jar.

**Comment by Papito541** [comment]
And how do I deactivate it?

**Comment by democat3457** [comment]
in the config?

**Comment by DemonfangArun** [comment]
Checking in to confirm that this is indeed working now :D
