### ISSUE TITLE
actual FutureMC version breaks villages trading

### ISSUE THREAD

**Issue by 1d01t** [thedarkcolour/Future-MC#273]
With the version:
future-mc-1.12.2-0.2.7.3.jar

it is not possible to open the trading gui for villagers.
When i click on a villager i get this error:

`[18:34:29] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerContainerEvent$Open@576b36cf:
java.lang.NoSuchMethodError: net.minecraft.inventory.Container.func_82847_b(Lnet/minecraft/inventory/IContainerListener;)V
        at thedarkcolour.futuremc.event.Events.onContainerOpen(Events.kt:352) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events.access$onContainerOpen(Events.kt:91) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events$registerEvents$$inlined$addListener$7.invoke(Util.kt:243) ~[Events$registerEvents$$inlined$addListener$7.class:0.2.7.3]
        at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.8-132.jar:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:919) ~[oq.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:273) ~[ady.class:?]
        at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
        at com.tmtravlr.potioncore.network.PacketHandlerServer.useEntity(PacketHandlerServer.java:96) ~[PacketHandlerServer.class:?]
        at com.tmtravlr.potioncore.network.PacketHandlerServer.lambda$onMessage$1(PacketHandlerServer.java:66) ~[PacketHandlerServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_302]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
[18:34:29] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[18:34:29] [Server thread/ERROR] [FML]: 0: NORMAL
[18:34:29] [Server thread/ERROR] [FML]: 1: ASM: class slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation onCraftingStationGuiOpened(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 2: ASM: class com.alcatrazescapee.alcatrazcore.network.capability.CapabilityContainerListenerManager$EventHandler onContainerOpenEvent(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 3: ASM: class com.feed_the_beast.ftbquests.util.ServerQuestData onContainerOpened(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 4: thedarkcolour.futuremc.event.Events$registerEvents$$inlined$addListener$7@4e19fcc9
[18:34:29] [Server thread/ERROR] [FML]: 5: ASM: crafttweaker.mc1120.events.CommonEventHandler@524df1b4 onPlayerOpenContainer(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 6: ASM: org.cyclops.cyclopscore.advancement.criterion.GuiContainerOpenTrigger@9e28f76 onEvent(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 7: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@1c14170e onContainerOpen(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 8: ASM: ru.socol.expandableinventory.registry.ModListener@13259bb0 onContainerOpen(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Open;)V
[18:34:29] [Server thread/ERROR] [FML]: 9: ASM: class mrriegel.instantunify.InstantUnify open(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent;)V
[18:34:29] [Server thread/ERROR] [FML]: 10: ASM: com.buuz135.togetherforever.action.AdvancementEventSyncAction@71ff228f onEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent;)V
[18:34:29] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.inventory.Container.func_82847_b(Lnet/minecraft/inventory/IContainerListener;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_302]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_302]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.NoSuchMethodError: net.minecraft.inventory.Container.func_82847_b(Lnet/minecraft/inventory/IContainerListener;)V
        at thedarkcolour.futuremc.event.Events.onContainerOpen(Events.kt:352) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events.access$onContainerOpen(Events.kt:91) ~[Events.class:0.2.7.3]
        at thedarkcolour.futuremc.event.Events$registerEvents$$inlined$addListener$7.invoke(Util.kt:243) ~[Events$registerEvents$$inlined$addListener$7.class:0.2.7.3]
        at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.8-132.jar:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:919) ~[oq.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:273) ~[ady.class:?]
        at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
        at com.tmtravlr.potioncore.network.PacketHandlerServer.useEntity(PacketHandlerServer.java:96) ~[PacketHandlerServer.class:?]
        at com.tmtravlr.potioncore.network.PacketHandlerServer.lambda$onMessage$1(PacketHandlerServer.java:66) ~[PacketHandlerServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_302]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
`

**Comment by 1d01t** [comment]
setting:
B:"New Villager Gui Screen"=false
on server and client does not help.

If i start the game without FutureMC the trading GUI will open.
