### ISSUE TITLE
Crash Pandas?

### ISSUE THREAD

**Issue by Azurewren** [thedarkcolour/Future-MC#28]
A think a panda is causing my world server to crash when I load in.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2019-07-18 23:20:10 AWST
Description: Ticking entity

java.lang.NoSuchMethodError: com.herobrine.future.entity.panda.EntityPanda.func_70016_h(DDD)V
    at com.herobrine.future.entity.panda.EntityPanda.func_213535_ey(EntityPanda.java:448)
    at com.herobrine.future.entity.panda.EntityPanda.onUpdate(EntityPanda.java:327)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zzj000(World.java:4118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by thedarkcolour** [comment]
Did you have the mod installed before 0.1.8? Try loading the world without the mod and then loading it again with the mod.

**Comment by thedarkcolour** [comment]
Can't reproduce, not enough information.
