### ISSUE TITLE
Minecraft Crash with the new 1.12.2 Update of Future-MC Version 0.2.16

### ISSUE THREAD

**Issue by Titoo8899** [thedarkcolour/Future-MC#344]
Hi, 
your new Version of your mod Crash by Loading of a world. I hope you can fix it and can give me a Fix Version to play it and give you feedback.

Her the Crash Report. I hope it help you:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  FutureMC (future-mc-0.2.16.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/1/24 11:25 AM
Description: Starting integrated server

java.lang.NoClassDefFoundError: net/minecraft/server/management/PlayerInteractionManager
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:58)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2369)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:734)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:249)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:168)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:117)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.management.PlayerInteractionManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer thedarkcolour.futuremc.asm.CoreTransformer@68c1112c from coremod FutureMC
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 23 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.item.ItemStack
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1728)
	at org.objectweb.asm.ClassWriter.getMergedType(ClassWriter.java:1698)
	at org.objectweb.asm.Frame.merge(Frame.java:1530)
	at org.objectweb.asm.Frame.merge(Frame.java:1429)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1516)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:835)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
	at thedarkcolour.futuremc.asm.ASMUtil.patch(ASMUtil.java:184)
	at thedarkcolour.futuremc.asm.ASMUtil.patch(ASMUtil.java:174)
	at thedarkcolour.futuremc.asm.CoreTransformer.transform(CoreTransformer.java:43)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:58)

-- Starting integrated server --
Details:
	Level ID: VVPP
	Level Name: VVPP
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2369)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:734)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:249)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:168)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:117)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiWorldSelection
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 263259744 bytes (251 MB) / 671088640 bytes (640 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forgelin  | 1.8.4        | Forgelin-1.8.4.jar            | None                                     |
	| LCHIJA | futuremc  | 0.2.6        | future-mc-0.2.16.jar          | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
FutureMC (future-mc-0.2.16.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.61' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.61, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700F

**Comment by krzj** [comment]
me too

**Comment by krzj** [comment]
https://mclo.gs/E8oxOXt
https://mclo.gs/QYVPVdC#L455
https://mclo.gs/EbPa2fQ

**Comment by Titoo8899** [comment]
Oh okay, I hope the Creater of this mod can fix the Problem. I love the idear but then the mod not work is it bad. And the new Changelog was cool then the Gamemodeswitcher function work.

**Comment by thedarkcolour** [comment]
I will fix today, sorry about this

**Comment by Titoo8899** [comment]
ah okay thanks for the answer and I was happy then the bug is fix.

**Comment by Titoo8899** [comment]
But I was so happy what you have in all the time have added to this good mod

**Comment by thedarkcolour** [comment]
Fixed in 0.2.17
