### ISSUE TITLE
Crash when placing lantern on Biomes O Plenty grass

### ISSUE THREAD

**Issue by VMan-2002** [thedarkcolour/Future-MC#68]
Crash log:
Description: Unexpected error

```java.lang.NullPointerException: Unexpected error
	at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:140)
	at thedarkcolour.futuremc.block.BlockLantern.isPiston(BlockLantern.java:54)
	at thedarkcolour.futuremc.block.BlockLantern.isBlockInvalid(BlockLantern.java:50)
	at thedarkcolour.futuremc.block.BlockLantern.canBlockStay(BlockLantern.java:63)
	at thedarkcolour.futuremc.block.BlockLantern.func_176196_c(BlockLantern.java:59)
	at net.minecraft.block.Block.func_176198_a(Block.java:655)
	at net.minecraft.world.World.func_190527_a(World.java:3187)
	at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:431)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:140)
	at thedarkcolour.futuremc.block.BlockLantern.isPiston(BlockLantern.java:54)
	at thedarkcolour.futuremc.block.BlockLantern.isBlockInvalid(BlockLantern.java:50)
	at thedarkcolour.futuremc.block.BlockLantern.canBlockStay(BlockLantern.java:63)
	at thedarkcolour.futuremc.block.BlockLantern.func_176196_c(BlockLantern.java:59)
	at net.minecraft.block.Block.func_176198_a(Block.java:655)
	at net.minecraft.world.World.func_190527_a(World.java:3187)
	at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:431)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
```

Produced with [https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/files/2715506](url) version of biomes o plenty

**Comment by thedarkcolour** [comment]
I will look into this when I get home.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thedarkcolour** [comment]
Can you post the entire crash log?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Queglar** [comment]
I was able to replicate the issue while testing compatibility with some other mods:

https://paste.dimdev.org/uyiperobef.mccrash

I tried a few different blocks from from vanilla and others, it only seems to trigger if you attempt to place the lantern on top of any variants of the BOP block biomesoplenty:grass (including the loamy or silty variants etc).

To be honest I'd also be happy for an option to disable the lantern entirely in the config.

**Comment by Queglar** [comment]
Oops - sorry, just found the config option # Whether the Lantern block is added to the game.
